export const EventType = {
  MESSAGE_CREATED: "MESSAGE_CREATED",
  MESSAGE_UPDATED: "MESSAGE_UPDATED",
  CHANNEL_CREATED: "CHANNEL_CREATED",
  HEARTBEAT: "HEARTBEAT",
  AUTHOR_UPDATED: "AUTHOR_UPDATED",
  MESSAGE_DELETED: "MESSAGE_DELETED",
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
